
name: firebase_auth_simplified_ui_example
description: Demonstrates the firebase_auth_simplified_ui package.

# Dart & Flutter constraints
environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.7.0'

#----------------------------
# Application dependencies
#----------------------------

dependencies:
  flutter:
    sdk: flutter

  # Firebase core & auth for the demo app
  firebase_core: ^3.15.1 
  firebase_auth: ^5.6.2

  # Local path reference to the package you are developing
  firebase_auth_simplified_ui:
    path: ../

#----------------------------
# Development dependencies
#----------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

#----------------------------
# Flutter asset configuration
#----------------------------

flutter:
  uses-material-design: true
  assets:
    - assets/demo.png
